# -*- coding: utf-8 -*-
"""BERT_Sentiment_Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6brhvvoEJag74uM6Mvhbm4Xke5YlFZH
"""

! nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/BERT/sentiment_classifier

!pwd

"""# Run the train"""

! pip install -q transformers

! python train.py

